### ISSUE TITLE
Reduce the number of compiler warnings

### ISSUE THREAD

**Issue by Schneegans** [cosmoscout/cosmoscout-vr#109]
Especially MSVC produces a lot of warnings. In fact there are so many warnings that we have to ignore them currently.

- [x] MSVC `/W3 /WX`
- [x] GCC `-Wall -Werror`
- [x] clang `-Wall -Werror`
- [ ] clang-tidy

**Comment by TheJhonny007** [comment]
Which warning level should we compile against? Microsoft recommends /W4, but default is /W3. 

I got the root repository to compile wit /W4 /WX, but there are some strange warnings in /W4 like unused parameters and stuff like that.

**Comment by Schneegans** [comment]
In my opinion, a clean complete /W3 build would be quite awesome already. I think we should aim for that first and see much work /W4 would create afterwards.

**Comment by TheJhonny007** [comment]
I think, if we want to keep `Werror` and `/WX` we need to integrate clang-tidy into the build chain. It catches most warnings independent of the compiler and prevents pushing code that doesn't work on other machines.

My initial attempt of integrating it failed, because it couldn't find the generated `*_export.hpp` header files.

**Comment by Schneegans** [comment]
I pushed an initial `clang-tidy.sh` script: https://github.com/cosmoscout/cosmoscout-vr/blob/feature/clang-tidy/clang-tidy.sh

It fixes a lot, but also prints bazillions of warnings. And it takes quite some time. Do you have a good idea how this could be integrated in out CI? Running it on every commit like and doing a git-diff afterwards will be quite costly.

If we disable some checks, we could also strive for zero warnings...

**Comment by TheJhonny007** [comment]
I will look into that monday. It is also possible to integrate clang-tidy with CMake easily.

CLion uses clang-tidy for it's suggestion and I'm quite happy with them. Maybe we can create a `.clang-tidy` file based on that. https://confluence.jetbrains.com/display/CLION/Clang-Tidy+in+CLion%3A+default+configuration

**Comment by TheJhonny007** [comment]
I integrated clang-tidy with CMake. It can be enabled with `-DCS_RUN_CLANG_TIDY=On` (default is of). It will also be disabled if clang-tidy isn't installed.

I tried replicating CLions .clang-tidy config, but was unsuccessful.

I think we should leave it disabled on the CI for now and slowly over time reduce the warnings. We may start with a single suggestion library and work our way forward. But I would prefer if #119 would be done first.

**Comment by TheJhonny007** [comment]
> And it takes quite some time.

If we take out `clang-analyzer` the performance is much better.

**Comment by TheJhonny007** [comment]
> And it takes quite some time. Do you have a good idea how this could be integrated in out CI?

Maybe we can disable it by default and run it before releases? This ensures that we only deploy safe code, but also enables fast development.

**Comment by Schneegans** [comment]
If integrated the way you suggest, we have to remove the `-fix` option as it seems to mess up files when building in parallel. I discovered that there is a script installed with clang-tidy which can be used to run clang-tidy in parallel. In our case:

`run-clang-tidy -fix -quiet -p build/linux-release`

What is even cooler: It uses our `compile_commands.json` which means that we do not have to configure any compiler options (includes, preprocessor flags, etc).

**Comment by TheJhonny007** [comment]
I tried the script and would suggest to use it in addition. With clang-tidy in CMake the IDE integration is much better. Since it is toggable I see no conflict in having both.

Regarding the `-fix` option I am fine with removing that for the CMake version.
