### ISSUE TITLE
Document the required libraries for Linux

### ISSUE THREAD

**Issue by TheJhonny007** [cosmoscout/cosmoscout-vr#115]
There are many distros of Linux with lots of different default packages. We should specify precisely which libraries need to be pre-installed.

**Comment by mikeblas** [comment]
True for Windows, too ... particularly with boost ... Which version is required?

**Comment by TheJhonny007** [comment]
I can't give a lowest number, but I know 1.69, 1.70 and 1.71 work.

**Comment by Schneegans** [comment]
**Regarding Boost on Windows**
Getting a precompiled version of Boost suitable for CosmoScout VR which will be found by CMake can be difficult: CMake fails to find versions which are too new; but on the other hand you need a rather new version if you use a very recent version of MSVC (e.g. 14.2, the one shipped with Visual Studio 2019). The "oldest" precompiled Boost which you can get on SourceForge for MSVC 14.2 is version 1.70.0.

So using version 1.70.0 may work in most cases. You can get it from from https://sourceforge.net/projects/boost/files/boost-binaries/1.70.0

MSVC | Visual Studio | File | Link
--- | --- | --- | ---
14.2 | 2019 | `boost_1_70_0-unsupported-msvc-14.2-64.exe` | [download](https://sourceforge.net/projects/boost/files/boost-binaries/1.70.0/boost_1_70_0-unsupported-msvc-14.2-64.exe/download)
14.1 | 2017 | `boost_1_70_0-msvc-14.1-64.exe` | [download](https://sourceforge.net/projects/boost/files/boost-binaries/1.70.0/boost_1_70_0-msvc-14.1-64.exe/download)
14.0 | 2015 | `boost_1_70_0-msvc-14.0-64.exe` | [download](https://sourceforge.net/projects/boost/files/boost-binaries/1.70.0/boost_1_70_0-msvc-14.0-64.exe/download)

**Regarding Linux Deps**
As there are many distributions with varying default libs and available packages, giving an exhaustive list will be difficult. But we could provide an exemplary list for Ubuntu 19.10 which users could adapt to their specific needs. I think this should be complete, but I am currently setting up a VM to test it:

```bash
sudo apt-get install git cmake build-essential xorg-dev libboost-dev
```

I will add these notes to the documentation once they are verified.

**Comment by Schneegans** [comment]
The above packages seem to work on Ubuntu 19.04 and 19.10. I created a PR which adds this documentation amongst other documentation updates: #116
