### ISSUE TITLE
Spdlog displays wrong log entries in debug.

### ISSUE THREAD

**Issue by TheJhonny007** [cosmoscout/cosmoscout-vr#126]
When running in debug spdlog always displays that the log event stems from the plugin that was loaded last.

**Comment by Schneegans** [comment]
Does this happen on Windows or Linux?

**Comment by TheJhonny007** [comment]
I last tested in with Linux and GCC.

**Comment by Schneegans** [comment]
I can confirm this. It doesn't happen on Windows though. I have to investigate why this happens 😃

**Comment by Schneegans** [comment]
It also happens when compiled with clang in release mode...

**Comment by Schneegans** [comment]
I addition, I noticed that using spdlog in header-only-mode (as we're doing right now) significantly increases build time (+70%). But the dll-local-registry only works in header-only-mode. Hence I will try to refactor the logging without using the registry at all...

**Comment by TheJhonny007** [comment]
> I addition, I noticed that using spdlog in header-only-mode (as we're doing right now) significantly increases build time (+70%). But the dll-local-registry only works in header-only-mode. Hence I will try to refactor the logging without using the registry at all...

We should also file a bug report on the official `spdlog` repo.

**Comment by Schneegans** [comment]
Regarding what?

**Comment by TheJhonny007** [comment]
> Regarding what?

That the dll-local-registry doesn't work in debug mode and clang. Or was that an error on our side?

**Comment by Schneegans** [comment]
That's a feature which only exists in our fork: https://github.com/cosmoscout/spdlog/tree/dll-local-registry

**Comment by TheJhonny007** [comment]
Oh, I didn't realize that we have a fork.
