### ISSUE TITLE
Dropdown menu don't fit in sidebar tab when there are too many options

### ISSUE THREAD

**Issue by gmate321** [cosmoscout/cosmoscout-vr#132]
## Describe the Bug

1. Start CosmoScout with full config
2. Go to Body settings
3. Open colormap dropdown
4. The bottom of the dropdown is not visible
5. When there are more options or the tab height is smaller, some elements of the tab and the dropdown menu become invisible

![2020-03-31_15h16_09](https://user-images.githubusercontent.com/62541989/78037755-3e78fc80-736c-11ea-988b-0db07998fbb6.png)
![2020-03-31_16h20_02](https://user-images.githubusercontent.com/62541989/78037759-3f119300-736c-11ea-83a6-1937bf3dce4c.png)

## Expected Behavior
Resize sidebar tab to fit the dropdown menu or scrollable dropdown.

**Comment by Schneegans** [comment]
Adding `data-container="#cosmoscout"` to the `select` fixes this. Once https://github.com/cosmoscout/cosmoscout-vr/pull/165 is merged, the styling will look better as well!
