### ISSUE TITLE
Precompiled Headers

### ISSUE THREAD

**Issue by JonasGilg** [cosmoscout/cosmoscout-vr#133]
CMake introduced precompiled headers in 3.16 (https://cmake.org/cmake/help/v3.16/command/target_precompile_headers.html#command:target_precompile_headers), which makes it possible to easily create them platform independently.

I think we should explore that to improve compile times (especially on Windows).

**Comment by TheJhonny007** [comment]
I just tested precompiled headers and another feature called unity builds on another project, which is using Qt5, spdlog, nlohmann-json, nholthaus-units and glm. Here are the compile times I measured with the different features enabeld/disabled:

 | PCH         | Unity Build | Compile Time |
 |:-----------:|:-----------:| ------------:|
 | Disabled    | Disabled    |      01:37 s |
 | Disabled    | __Enabled__ |      00:32 s |
 | __Enabled__ | Disabled    |      00:26 s |
 | __Enabled__ | __Enabled__ |      00:20 s |

So with both features enabled I could cut the compile time on Windows by 80%. This should be reason enough to try this with CosmoScout VR.

**Comment by TheJhonny007** [comment]
Externals are now compiled with unity builds and precompiled headers where possible.
