### ISSUE TITLE
Planet labels displayed incorrectly at high simulation speeds

### ISSUE THREAD

**Issue by NXXR** [cosmoscout/cosmoscout-vr#136]
## Description
At high simulation speeds (Month/s), the labels of some planets (earth and planets further from the sun) are oriented incorrectly or changing orientation rapidly, making them unreadable or hard to read.
**Issue only appears at Month/s simulation speed (and -Month/s), slowing down to Day/s instantly reorients the labels properly.**
![CSVR_label_display_bug](https://user-images.githubusercontent.com/25636783/78376045-0cff6b80-75ce-11ea-9caf-f4e91abc0259.png)
![CSVR_label_display_bug2](https://user-images.githubusercontent.com/25636783/78376054-1092f280-75ce-11ea-9b09-5bd9a020f402.png)

1. zoom out to a location with an overview of planet orbits around the sun.
2. increase simulation speed to Month/s.

## Expected Behavior
Display labels with fixed orientation to the observer to increase readability.

## System
 - CosmoScout VR version 1.2.0
 - OS: Windows 10
 - Compiler: MSVC 14.16.27023
 - Graphics Card: NVIDIA GeForce GTX 1070

**Comment by Schneegans** [comment]
Thanks for the report! This may be related to an issue I observed the other day: If you rotate a planet really quickly it seems that the sun direction lags behind for one frame. Maybe there is an update-order issue. I will look into this.
