### ISSUE TITLE
Add unified bookmarks system

### ISSUE THREAD

**Issue by Schneegans** [cosmoscout/cosmoscout-vr#144]
## The Problem
The current *Events* on the time line and the *Locations* of `csp-fly-to-locations` are kind of similar things, especially once it's possible to save them to file.

## The Solution
I would propose to implement a unified bookmark system. A bookmark could consist of a name, a description, a location, a time point and potentially also a duration. Most of these fields could be optional. The `csp-fly-to-locations` plugin would show all bookmarks with a location on the current planet; the timeline could show all bookmarks having a time point. There should be one *add-bookmark-dialog* in `cs-core` which could be used when double-clicking on the timeline and when adding a new bookmark with the `csp-fly-to-locations` plugin.

If anybody wants to start working on this, you should base your work on the `feature/save-scene` branch if it's not merged already.

**Comment by TheJhonny007** [comment]
I think this can be closed.
