### ISSUE TITLE
JSON Version doesn't work with gcc-10.1.0 in Release 1.2.0

### ISSUE THREAD

**Issue by JonasGilg** [cosmoscout/cosmoscout-vr#188]
## Describe the Bug
The 1.2.0 version can't  be compiled with gcc-10.1.0, because the version of nlohman json throws build errors during `make.sh`

See this issue: https://github.com/nlohmann/json/issues/1920

## System
 - CosmoScout VR version: 1.2.0
 - OS: Ubuntu 18.04
 - Compiler: gcc-10.1.0

**Comment by Schneegans** [comment]
With the current develop (and soon v1.3.0) branch, this is not a problem for me. Can we close this?
