### ISSUE TITLE
Version 1.2 Hotfix

### ISSUE THREAD

**Issue by JonasGilg** [cosmoscout/cosmoscout-vr#189]
The version 1.2 doesn't work with updated tools like CMake 3.17+ and GCC-10.1.0.

See issues:
- #187
- #188
- #176
- #185

Most of these issues are not present with GCC-Version 7 and 8. Do we want to backport fixes for these to version 1.2 or should we only support newer GCC versions from version 1.3 onwards?

What do you think @Schneegans?

**Comment by Schneegans** [comment]
I would go for the latter. Version 1.3 can be released quite soonishly. At this point, I would suggest to everyone who wants to play with the software to use the current develop branch anyways as it contains so many new features.
