### ISSUE TITLE
[LOD Bodies] Docker Mapserver

### ISSUE THREAD

**Issue by octfx** [cosmoscout/cosmoscout-vr#242]
For ease of use, I've created a dockerized version of the mapserver described in the LOD Bodies documentation.
The repository is located [here](https://github.com/octfx/csp-lod-bodies-mapserver).

Also, GitHub actions will automatically build the image which is accessible by pulling `octfx/lod-bodies-mapserver`.

Local tests were successful, although sometimes `Tile loading failed: ëPNG` was logged.

I don't know if it's usefull enough to be added to the documentation, but it might help for future reference.

**Comment by Schneegans** [comment]
Thanks again for this idea! We created a container for the map server. The documentation is still WIP, but you can already find it here: https://github.com/cosmoscout/docker-mapserver/
