### ISSUE TITLE
Install third-party libraries to install directory on windows

### ISSUE THREAD

**Issue by Flatken** [cosmoscout/cosmoscout-vr#253]
## Describe the Bug
When I am building CosmoScout VR from the command line on windows using make_externals.bat and then calling make.bat, the third-party libraries from the externals lib and bin directory and not copied into the CosmoScout VR install lib folder.

1. call make_externals.bat
2. call mae.bat
3. look into the install lib folder of CosmoScout VR and look e.g. for the ViSTA libraries

I tested with Jonas the following!
Calling "file(TO_CMAKE_PATH ${COSMOSCOUT_EXTERNALS_DIR} COSMOSCOUT_EXTERNALS_DIR)" in CMakeList will fix the issue

## Expected Behavior
All libs including e.g. the DriverPlugins folder of ViSTA should be copied to the CS install lib folder

## System
_Please complete the following information:_
 - CosmoScout VR version 1.3.0
 - OS: Windows 10
 - Compiler:  VS 2017 with compiler
 - Graphics Card: Quadro P3200

**Comment by JonasGilg** [comment]
My bad, I forgot to merge develop into feature/guide. 🙈
