### ISSUE TITLE
Rings as Eclipse Shadow Receiver

### ISSUE THREAD

**Issue by JonasGilg** [cosmoscout/cosmoscout-vr#281]
It would be nice, if rings also receive eclipse shadows.

**Comment by JonasGilg** [comment]
> I think I have an idea how this could be fixed. Did you push your changes already?

Yes, they are on this branch: https://github.com/cosmoscout/cosmoscout-vr/tree/feature/ring-eclipses

Sadly I accidentally branched from the `more-simple-bodies` branch, so we shouldn't merge this before the other branch is merged.

**Comment by Schneegans** [comment]
I think we can close this now.
