### ISSUE TITLE
Sun shines through lod mountains 

### ISSUE THREAD

**Issue by carlobrok** [cosmoscout/cosmoscout-vr#292]
## Describe the Bug
On lod Mars, the sun shines through the mountains when they are partially obscured by other mountains.

1. using full_desktop.json
2. Go to gale crater on the small ridge roughly at the marked location
3. Look in the marked location so you can see the distant mountains
4. Set the time to 2022-07-14 11:00:00 
5. (Fly up and down)

![Screenshot from 2022-07-14 15-48-04](https://user-images.githubusercontent.com/44724164/179000483-7c95e757-ddcc-400c-8f8a-dd24fa69cc2a.png)

## Expected Behavior
When you are close to the ground, you will see the sun shining through the distant mountains.

![mars_sonne_sichtbar_nach_untergang](https://user-images.githubusercontent.com/44724164/179000642-dc4014be-6922-4139-80de-cbfba72b3651.png)

The mountains will block the sun as you're higher off the ground. Shown below:

![Screenshot from 2022-07-14 15-19-38](https://user-images.githubusercontent.com/44724164/179001133-a9ad624e-e37b-4595-a93c-8b9bad4af684.png)
![Screenshot from 2022-07-14 15-19-07](https://user-images.githubusercontent.com/44724164/179001144-5b2244ed-ccb9-4f72-82e9-de30342c91ff.png)
![Screenshot from 2022-07-14 15-19-19](https://user-images.githubusercontent.com/44724164/179001153-fdcde408-1b20-4ad2-aea4-3d5c455b4cf6.png)

**Comment by JonasGilg** [comment]
Very interesting find. Maybe this has something todo with the new reverse projection @Schneegans?
