### ISSUE TITLE
Compiling with VS 2017 under Windows fails because of unkown commandline argument of cmake

### ISSUE THREAD

**Issue by StefanLobas** [cosmoscout/cosmoscout-vr#3]
I added the cmake to my PATH enviroment variable to start compiling but make_externals.bat failed due to the invalid parameter "--parallel 8". After removing the argument, make_externals.bat just works fine.

**Comment by StefanLobas** [comment]
Reading the documentation clearly states the version of cmake needed...

**Comment by Simmesimme** [comment]
Great that it worked for you! Just for future reference: Which version of cmake did you use at first?

**Comment by StefanLobas** [comment]
It was version 3.6 which was shipped with VS 2017.
