### ISSUE TITLE
Simple dependency management between plugins

### ISSUE THREAD

**Issue by JonasGilg** [cosmoscout/cosmoscout-vr#301]
## The Problem
We want to create a new plugin, that combines data from WMS, WCS and WFS sources that also implements some analysis tools ontop. We currently have a plugin to load WMS data and [a WCS plugin is also in the vestec branch](https://github.com/cosmoscout/cosmoscout-vr/tree/feature/vestec/plugins/csp-wcs-overlays). 

Currently it is not easily possible to have dependencies between plugins, which initially was also by design, but it would also be code smell to duplicate all this plugin code.

## The Solution
Create a small dependency system, that would allow plugins to depend on other plugins.

Things to consider:
- Plugin dependencies have to be declared in the config
- A dependency tree has to be created and the plugins have to be loaded in the correct order
- Plugins should have a headless mode, where the DLL is loaded, but the plugin is not initialized, so they function more like a library

## The Alternatives
- Copy and paste the required code to the new plugin
- Put some of the wms/wcs/wfs features into CosmoScout core
- Create some kind of data sharing feature in CosmoScout core

**Comment by JonasGilg** [comment]
Current idea is, to create a new system for "plugin-libraries" short `csl`. They will also be situated in the plugins folder.
Plugin libraries will have no subclass of `Plugin`, but can have their own logger. They can just be linked against from other plugins.

**Comment by Schneegans** [comment]
I think we could move the measurement tools base classes to such a "plugin-library". They are currently only used in plugins.
