### ISSUE TITLE
Loading settings from local json inconsistent

### ISSUE THREAD

**Issue by MutterOberin** [cosmoscout/cosmoscout-vr#326]
## Describe the Bug

When using a local settings file (generated via core.save callback) scene state does not reflect settings completely. Specific example is the "lodFactor".

**Comment by JonasGilg** [comment]
I think the issue here is that the lodFactor is not user configurable at all (except if you put it on manual mode in the UI), because it is supposed to always adjust to the most optimal setting.

We could add a config option that could look like this:

```ts
'lodFactor': <number> or <string>
```

with accaptable values: 'auto', 10 - 50.

**Comment by JonasGilg** [comment]
I am mistaken, `lodFactor` and `autoLod` already are being serialized and deserialized. Then this is indeed a bug.
