### ISSUE TITLE
csp-stars fail to initialize - not displayed

### ISSUE THREAD

**Issue by Sasatari** [cosmoscout/cosmoscout-vr#334]
Starts and runs, but shows no stars.
Shell throws:
`[W] cosmoscout-vr ..... Failed to initialize plugin 'csp-stars': bad allocation`

New to cosmoscout vr, couldn´t change the simple_desktop.json successfully, a settings.json doesn´t exist.

Checked existense of files which are linked in the json. They all are in the right location.

Effect is, that everything runs fine as far as I can tell, but it doesn´t show any stars.

Downloaded latest binary today, installed on a Ryzen Threadripper PRO 3955WX, 128GB and RTX3080.

## System
 - CosmoScout VR v1.7.0 (binary, not self compiled)
 - OS: Windows 10 Pro, 22H2
 - Compiler: not applicable, downloaded binary
 - CPU: AMD Ryzen Threadripper PRO 3955WX
 - Graphics Card: NVidia RTX 3080

**Comment by Schneegans** [comment]
Hi there; thanks for the report! The first thing I can think of is that maybe the star data got somehow corrupted while downloading. In the `share\download\stars` directory should be two files: `hip_main.dat` (\~53 MB) and `tyc2_main.dat` (\~528 MB). Do they exist? If they are smaller, maybe you should delete them and CosmoScout will re-download them upon the next launch.

Also, you could try deleting the file `bin\star_cache.dat` in case this is somehow corrupted. If both approaches do not help, we have to investigate further :wink:

**Comment by Sasatari** [comment]
Success. The files were existing and slightly smaller. But after deleting them, they were downloaded again in the same size, but this time they are correctly and fully displayed.

Case solved. I C stars. Thanks!
