### ISSUE TITLE
NOOB ALERT: Seeking to dynamically add transformations on satellites (if possible)

### ISSUE THREAD

**Issue by jeveloper** [cosmoscout/cosmoscout-vr#375]
## The Problem
An ability to dynamically launch transformations on satellites (existing or new).

## The Solution
Seeking for vague or solid suggestions.
I am willing to sponsor this work, objectively out of my own pocket so I might get cheap (forgive me). 

## The Alternatives

Not sure.

Thank you for reading

**Comment by Schneegans** [comment]
Hi there! Thank you for checking out CosmoScout VR! I do not fully understand what you are looking for. Satellites in CosmoScout are controlled via [SPICE kernels](https://naif.jpl.nasa.gov/naif/aboutspice.html). So if you have such a kernel for a given space mission, you could use this to place a 3D satellite at the corresponding position in space and time.

Adding satellites to arbitrary positions in space and time is not really possible right now. Do you want this?

Or would you rather be interested in moving parts of a satellite? Like cameras, antennas, etc?

**Comment by jeveloper** [comment]
Hello @Schneegans  Simon, Sorry for the delayed response. 

I understood what you meant, so I would create a mission in the format of spice kernels and load it up into the scene at runtime. 

The concept of understanding this is, can I as a viewer generate satellites and load it at runtime and have my camera move toward them at a certain rate.

**Comment by Schneegans** [comment]
If you have 
* a SPICE kernel describing the orbit or trajectory of your satellite, and
* a glTF 3D model for the satellite

you can add them to your scene description. If you have the kernel and a 3D model, I could provide you the details on what to add into which file. Then you can open CosmoScout VR and the satellite should travel along the path defined by the SPICE kernel.

**Comment by jeveloper** [comment]
@Schneegans Simon, thank you kindly! 
This is a somewhat low priority project on my end as an artist/software engineer. I do have plan in H1 of 2025 to set up the space for this (for other people).
Can I follow up then and is there a good way of doing it? Email

**Comment by Schneegans** [comment]
You can always reach us via cosmoscout@dlr.de!

**Comment by jeveloper** [comment]
Thank you kindly! 
The vision is setting up a comfortable experience for people in my community and making it basic operations. Ideally if I can have someone helping me run it and figure out funding to operate a small space. I live up in Yukon :) Explored Germany about 22 separate trips :)))

**Comment by jeveloper** [comment]
Hello @Schneegans  Simon
I wanted to follow up. I did want to contribute a series of music parts to the project, I will be waiting to plan that once you launch the next one (January x? ).
I have  sent an email last year about sounds and music.

**Comment by JonasGilg** [comment]
> Hello [@Schneegans](https://github.com/Schneegans) Simon I wanted to follow up. I did want to contribute a series of music parts to the project, I will be waiting to plan that once you launch the next one (January x? ). I have sent an email last year about sounds and music.

Hi, I have taken over the lead from Schneegans. Can you contact me via Email on Jonas.Gilg@dlr.de? We can then discuss further steps.

**Comment by jeveloper** [comment]
@JonasGilg  Thank you for following up (of all places in GitHub). Danke ( I am assuming a German speaker). 
I live in the arctic region in Canada and some of my creative/work plans have been shifted by a week or two. -40C interrupts a lot

**Comment by jeveloper** [comment]
I'll send a short email to connect and then follow up.
