### ISSUE TITLE
Remove shader uniform location queries in the frame loop

### ISSUE THREAD

**Issue by JonasGilg** [cosmoscout/cosmoscout-vr#62]
A lot of shaders are querying the location of uniforms every frame, which should be avoided.
The uniform locations should be queries once after the shader has been linked and saved for reuse.

I propose the following convention for caching uniforms in a render class.

```c++
class SomeRenderer : public IVistaOpenGLDraw {
  public:
    SomeRenderer() {
        /* compile shader and link shader */
        mUniforms.mvp = glGetUniformLocation(mShader, "uMVP");
        mUniforms.color = glGetUniformLocation(mShader, "uColor");
        mUniforms.sunLocation = glGetUniformLocation(mShader, "uSunLocation");
    }

    /* ... */
  private:
    /* ... */

    uint32_t mShader;

    struct {
        uint32_t mvp;
        uint32_t color;
        uint32_t sunLocation;
    } mUniforms;
}
```

### cs-core
- [ ] tools/Mark.cpp

### cs-graphics
- [ ] MouseRay.cpp

### cs-gui
- [ ] ScreenSpaceGuiArea.cpp
- [ ] WorldSpaceGuiArea.cpp
- [ ] SpriteGui.cpp

### cs-scene
- [ ] Trajectory.cpp

### csp-atmospheres
- [ ] VistaAtmosphere.cpp

### csp-lod-bodies
- [ ] TileRenderer.cpp
- [ ] PlanetShader.cpp

### csp-measurement-tools
- [ ] PolygonTool.cpp
- [ ] DipStrikeTool.cpp
- [ ] EllipseTool.cpp
- [ ] PathTool.cpp

### csp-rings
- [ ] Ring.cpp

### csp-sharad
- [ ] Sharad.cpp

### csp-simple-bodies
- [ ] SimpleBody.cpp

### csp-stars
- [ ] Stars.cpp

### csp-trajectories
- [ ] DeepSpaceDot.cpp
- [ ] SunFlare.cpp

**Comment by Schneegans** [comment]
This is definitely required. Usually, this should be in the scope of the OpenGL wrapper, but until we have a proper replacement for ViSTA, we could use the proposed approach.

**Comment by TheJhonny007** [comment]
I will try and do it in conjunction with issue #27, since these issues are closely related.

**Comment by TheJhonny007** [comment]
> This is definitely required. Usually, this should be in the scope of the OpenGL wrapper, but until we have a proper replacement for ViSTA, we could use the proposed approach.

Should we write our own OpenGL wrapper? At least for Shaders and Uniforms?
This would ensure modern C++ everywhere and if the interface is missing something we can change it anytime.

I am currently writing a lot of redundant code. (Even ViSTA doesn't abstract uniforms very well.)

**Comment by Schneegans** [comment]
I don't think that this is a good idea.

**The obvious reason**: Writing Yet Another OpenGL Wrapper™ feels like re-inventing the wheel for the 100th time... There are _tons_ out there.

https://oglplus.org/
https://github.com/Overv/OOGL
https://github.com/Tomius/oglwrap
...

**Another reason** is neatly formulated by [some guy on reddit](https://www.reddit.com/r/opengl/comments/8wos9k/opengl_wrapper_library/):

> OpenGL's stateful design doesn't lend itself to being nicely wrapped in an "object oriented" manner. This makes all GL wrappers more or less leaky abstractions and they might cause more problems than they solve. The DSA (direct state access) API helps a little, but does not completely remove the global state.
> 
> Everyone who has done GL programming (me included) has wasted a lot of effort trying to implement some kind of wrapper, but most people sooner or later figure out it's a futile effort. GitHub is full of half-assed wrapper libraries that probably did not save the author any time or effort compared to just using "raw" opengl calls.
> 
> Here's my recommendations based on almost 20 years of GL programming experience (feel free to disagree):
> 
> 1. Don't use a low-level wrapper utility. Build your abstractions at a higher level. Don't write classes for "buffer", "texture", "framebuffer" etc. Abstract at a higher level taking your application specific requirements into account. "Model", "Material", "Lighting", "Instance", "Scene", etc.
> 2. If you insist on using a wrapper, take a full-blown API abstraction layer with backends for other APIs too (d3d, metal, etc). Pick one that is used by more than one person. E.g. this is popular: https://github.com/bkaradzic/bgfx
>  3. Consider using Vulkan instead. It's a much more sanely designed API (not without its warts) without a global state. There are wrappers around Vulkan which are much more sane than GL wrappers but I'd just use the C API as is.

BTW, the framework he linked above is definitely worth looking at!

**Last but not least**, if we ever decide to move away from ViSTA to a more modern framework, all this work would be for nothing. So in my opinion, we should focus on that discussion in the first place.

What do you think?

**Comment by Schneegans** [comment]
I would suggest to move this issue to v1.3.0. What do you think?

**Comment by TheJhonny007** [comment]
Yes, this sounds good.

**Comment by Schneegans** [comment]
Can we close this, @JonasGilg ?

**Comment by JonasGilg** [comment]
> Can we close this, @JonasGilg ?

Yes, I thought it would auto close since it was linked to the pull request...
