### ISSUE TITLE
Wrong focus after fly-to feature was used.

### ISSUE THREAD

**Issue by JonasGilg** [cosmoscout/cosmoscout-vr#75]
## Describe the Bug
Using the fly-to-locations feature with MSL results in MSL always having the focus for rotation.

1. Go to fly to locations in the GUI
2. Click MSL
3. Zoom out
4. Try to rotate around Mars with left click pressed

## Expected Behavior
The rotational center should be Mars when zooming out.

## System
 - CosmoScout VR version 1.1.0
 - OS: SLED12
 - Compiler: GCC 8.1.0
 - Graphics Card: NVIDIA QUADRO P6000

**Comment by Schneegans** [comment]
Thanks for reporting the issue! Let's see how we can fix it :smile:

**Comment by Schneegans** [comment]
This seems to got fixed on-the-way. I cannot reproduce it anymore. The SPICE frame transitions have been refactored, maybe this fixed this bug as well?

**Comment by JonasGilg** [comment]
I can confirm that this is no longer an issue.
