### ISSUE TITLE
Add minutes in time speed steps.

### ISSUE THREAD

**Issue by TheJhonny007** [cosmoscout/cosmoscout-vr#84]
Currently the time speed is goes from realtime directly to hours, which in some applications is to coarse.

I suggest adding minutes to the possible speeds.

**Comment by Schneegans** [comment]
Good point!

**Comment by TheJhonny007** [comment]
The available time steps could maybe be specified in the config?

**Comment by Schneegans** [comment]
I think adding this time speed will be sufficient for now. We can make this configurable if it is really required by some project.

**Comment by Schneegans** [comment]
Done in https://github.com/cosmoscout/cosmoscout-vr/pull/91
