### ISSUE TITLE
Eclipses

### ISSUE THREAD

**Issue by JonasGilg** [cosmoscout/cosmoscout-vr#85]
The following things need to be done:

#### All eclipses
- [ ] Integrate limb darkening.
- [ ] Cache the shadow textures for reuse.
- [ ] Generate lookup textures at perihelion and aphelion and interpolate between them to get better results for eccentric orbits.
- [ ] The shadow textures should have an exponential scale on the vertical axis with the origin at the start of the penumbra.
- [ ] The [eclipse shader extension](https://github.com/cosmoscout/cosmoscout-vr/blob/feature/eclipses/resources/shaders/EclipseShadowsLib.glsl) should use prefixes for all definitions to avoid name collisions.

#### Eclipses without atmospheres
- [ ] The ray tracer needs to work in 3D.
- [x] Fix the wrong conversion factor in the [photon tracer shader](https://github.com/cosmoscout/cosmoscout-vr/blob/feature/eclipses/resources/shaders/EclipsePhotonTracer.glsl).
- [x] Do all calculations in double precision.
- [ ] The lookup tables for the density and refractive indices should be a texture instead of an SSBO.
- [ ] Move the texture tracing to the GPU. ([NVIDIA has atomic floats](https://www.khronos.org/registry/OpenGL/extensions/NV/NV_shader_atomic_float.txt))
- [ ] (To enhance precision it might be worth having the origin at the bottom of the atmosphere instead of the body center.)

#### Eclipses with atmospheres
- [ ] Generation of texture can be done on the GPU with a compute shader.

**Comment by Schneegans** [comment]
I think we can close this as the new implementation will be quite different.
