### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by TheJhonny007** [cosmoscout/cosmoscout-vr#90]
Add unit testing to CosmoScout VR.

Things to consider:
- Which framework to use?
  - Google Test
  - Boost.Test
  - Catch
  - DocTest
  - ...
- What scope?
  - Unit Tests?
  - Integration Tests?
- Make runs mandatory or optional.
- Include into GitHub Actions?
- How to integrate into the project
  - Test suit per module?
  - What about plugins?

**Comment by Schneegans** [comment]
I vote for DocTest. There is also an example for running test from shared objects and plugins: https://github.com/onqtam/doctest/tree/master/examples/executable_dll_and_plugin

We could write the tests in a dedicated `tests.cpp` for each module / plugin. Then a flag `--run-tests` of the `cosmoscout` executable could run all tests. This could be available in debug mode only.
