### ISSUE TITLE
MSVC Version

### ISSUE THREAD

**Issue by TheJhonny007** [cosmoscout/cosmoscout-vr#93]
In the [build instructions](https://github.com/cosmoscout/cosmoscout-vr/blob/master/docs/install.md#build-instructions) documentation it says that the required MSVC version is `msvc 19`, but the default in the `make*.bat` files is still `Visual Studio 15 Win64`. Also the section on [building](https://github.com/cosmoscout/cosmoscout-vr/blob/master/docs/install.md#windows) cosmoscout for windows uses `Visual Studio 15 Win64`.

What are the correct requirements?

**Comment by Schneegans** [comment]
Both are correct. Visual Studio 15 uses msvc 19.

**Comment by TheJhonny007** [comment]
Oh yeah, I forgot about Windows horrendous versioning system. So the minimum version would be this: `MSVC++ 14.0, _MSC_VER == 1900, (Visual Studio 2015 version 14.0)`.
